/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  careersSidebar: [{type: 'autogenerated', dirName: 'hr'}],
  technologySidebar: [{type: 'autogenerated', dirName: 'technology'}],
  deliverySidebar: [{type: 'autogenerated', dirName: 'delivery'}],
  operationsSidebar: [{type: 'autogenerated', dirName: 'operations'}],
  legalSidebar: [{type: 'autogenerated', dirName: 'legal'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
